(define (domain block-mover)
(:predicates (block ?b) (table ?t) (on ?x ?y) (clear ?b) (isequal ?x ?y))

(:action move
 :parameters (?b ?x ?y)
 :precondition (and (on ?b ?x)
                    (clear ?b)
                    (clear ?y)
                    (block ?b)
                    (block ?y)
                    (not (isequal ?b ?x))
                    (not (isequal ?b ?y))
                    (not (isequal ?y ?x)))
 :effect (and (on ?b ?y)
              (clear ?x)
              (not (on ?b ?x))
              (not (clear ?y))) )

(:action movetotable
 :parameters (?b ?x ?t)
 :precondition (and (on ?b ?x)
                    (clear ?b)
                    (block ?b)
                    (block ?x)
                    (not (isequal ?x ?b))
                    (table ?t))
 :effect (and (on ?b ?t)
              (clear ?x)
              (not (on ?b ?x))) )