(define (problem block-mover-problem)
(:domain block-mover)
(:objects blocka blockb blockc tablet)
(:init (block blocka)
       (block blockb)
       (block blockc)
       (table tablet)
       (on blocka tablet)
       (on blockb tablet)
       (on blockc blocka)
       (clear blockb)
       (clear blockc))

(:goal (and (on blocka blockb)
            (on blockb blockc)))