(define (problem air-transport-problem)
(:domain air-transport)
(:objects cargo1 cargo2 SFO JFK plane1 plane2)
(:init (plane plane1)
       (plane plane2)
       (airport SFO)
       (airport JFK)
       (cargo cargo1)
       (cargo cargo2)
       (at cargo1 SFO)
       (at cargo2 JFK)
       (at plane1 SFO)
       (at plane2 JFK))
(:goal (and (at cargo1 JFK)
            (at cargo2 SFO))) )